# Generated by Django 4.2.29 on 2026-03-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lejos_od_esf', models.CharField(blank=True, max_length=10)),
                ('lejos_od_cil', models.CharField(blank=True, max_length=10)),
                ('lejos_od_eje', models.CharField(blank=True, max_length=10)),
                ('lejos_od_dp', models.CharField(blank=True, max_length=10)),
                ('lejos_oi_esf', models.CharField(blank=True, max_length=10)),
                ('lejos_oi_cil', models.CharField(blank=True, max_length=10)),
                ('lejos_oi_eje', models.CharField(blank=True, max_length=10)),
                ('lejos_oi_dp', models.CharField(blank=True, max_length=10)),
                ('cerca_od_esf', models.CharField(blank=True, max_length=10)),
                ('cerca_od_cil', models.CharField(blank=True, max_length=10)),
                ('cerca_od_eje', models.CharField(blank=True, max_length=10)),
                ('cerca_od_dp', models.CharField(blank=True, max_length=10)),
                ('cerca_oi_esf', models.CharField(blank=True, max_length=10)),
                ('cerca_oi_cil', models.CharField(blank=True, max_length=10)),
                ('cerca_oi_eje', models.CharField(blank=True, max_length=10)),
                ('cerca_oi_dp', models.CharField(blank=True, max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente')),
            ],
        ),
    ]
