# Generated by Django 4.2.29 on 2026-03-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('institucion', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(choices=[('XV', 'XV - Arica y Parinacota'), ('I', 'I - Tarapacá'), ('II', 'II - Antofagasta'), ('III', 'III - Atacama'), ('IV', 'IV - Coquimbo'), ('V', 'V - Valparaíso'), ('RM', 'RM - Metropolitana'), ('VI', "VI - O'Higgins"), ('VII', 'VII - Maule'), ('XVI', 'XVI - Ñuble'), ('VIII', 'VIII - Biobío'), ('IX', 'IX - La Araucanía'), ('XIV', 'XIV - Los Ríos'), ('X', 'X - Los Lagos'), ('XI', 'XI - Aysén'), ('XII', 'XII - Magallanes')], max_length=5)),
                ('anamnesis', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
