# Generated by Django 4.2.29 on 2026-03-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='institucion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
